export interface FranchiseInfo {
  abbrev: string
  name: string
  foundedYear: number
  arena: string
  city: string
  isDefunct?: boolean
  yearsActive?: string        // e.g. "1979–1997"
  franchiseId?: number        // NHL stats API franchise group
  previousNames?: { name: string; years: string }[]
}

// franchiseId → ordered list of triCodes (chronological within franchise)
export const FRANCHISE_CHAINS: Record<number, string[]> = {
  3:  ['SEN', 'SLE'],                          // Ottawa Senators (1917) → St. Louis Eagles
  4:  ['QBD', 'HAM'],                          // Quebec Bulldogs → Hamilton Tigers
  5:  ['TAN', 'TSP', 'TOR'],                   // Toronto Arenas → St. Patricks → Maple Leafs
  7:  ['MMR'],                                 // Montreal Maroons (standalone defunct)
  8:  ['NYA', 'BRK'],                          // NY Americans → Brooklyn Americans
  9:  ['PIR', 'QUA'],                          // Pittsburgh Pirates → Philadelphia Quakers
  12: ['DCG', 'DFL', 'DET'],                   // Detroit Cougars → Falcons → Red Wings
  13: ['OAK', 'CGS', 'CLE'],                   // Oakland Seals → California Seals → Cleveland Barons
  15: ['MNS', 'DAL'],                          // Minnesota North Stars → Dallas Stars
  21: ['AFM', 'CGY'],                          // Atlanta Flames → Calgary Flames
  23: ['KCS', 'CLR', 'NJD'],                   // Kansas City Scouts → Colorado Rockies → NJ Devils
  26: ['HFD', 'CAR'],                          // Hartford Whalers → Carolina Hurricanes
  27: ['QUE', 'COL'],                          // Quebec Nordiques → Colorado Avalanche
  28: ['WIN', 'PHX', 'ARI'],                   // Winnipeg Jets (1979) → Phoenix → Arizona Coyotes
  35: ['ATL', 'WPG'],                          // Atlanta Thrashers → Winnipeg Jets
  40: ['UTA'],                                 // Utah HC / Mammoth (new franchise 2024)
}

export const FRANCHISE_INFO: Record<string, FranchiseInfo> = {
  // ─── Current 32 NHL Teams ───────────────────────────────────────────────
  ANA: {
    abbrev: 'ANA',
    name: 'Anaheim Ducks',
    foundedYear: 1993,
    arena: 'Honda Center',
    city: 'Anaheim, CA',
    franchiseId: 32,
    previousNames: [{ name: 'Mighty Ducks of Anaheim', years: '1993–2006' }],
  },
  BOS: {
    abbrev: 'BOS',
    name: 'Boston Bruins',
    foundedYear: 1924,
    arena: 'TD Garden',
    city: 'Boston, MA',
    franchiseId: 6,
  },
  BUF: {
    abbrev: 'BUF',
    name: 'Buffalo Sabres',
    foundedYear: 1970,
    arena: 'KeyBank Center',
    city: 'Buffalo, NY',
    franchiseId: 19,
  },
  CAR: {
    abbrev: 'CAR',
    name: 'Carolina Hurricanes',
    foundedYear: 1997,
    arena: 'Lenovo Center',
    city: 'Raleigh, NC',
    franchiseId: 26,
    previousNames: [{ name: 'Hartford Whalers', years: '1979–1997' }],
  },
  CGY: {
    abbrev: 'CGY',
    name: 'Calgary Flames',
    foundedYear: 1980,
    arena: 'Scotiabank Saddledome',
    city: 'Calgary, AB',
    franchiseId: 21,
    previousNames: [{ name: 'Atlanta Flames', years: '1972–1980' }],
  },
  CHI: {
    abbrev: 'CHI',
    name: 'Chicago Blackhawks',
    foundedYear: 1926,
    arena: 'United Center',
    city: 'Chicago, IL',
    franchiseId: 11,
  },
  COL: {
    abbrev: 'COL',
    name: 'Colorado Avalanche',
    foundedYear: 1995,
    arena: 'Ball Arena',
    city: 'Denver, CO',
    franchiseId: 27,
    previousNames: [{ name: 'Quebec Nordiques', years: '1979–1995' }],
  },
  CBJ: {
    abbrev: 'CBJ',
    name: 'Columbus Blue Jackets',
    foundedYear: 2000,
    arena: 'Nationwide Arena',
    city: 'Columbus, OH',
    franchiseId: 36,
  },
  DAL: {
    abbrev: 'DAL',
    name: 'Dallas Stars',
    foundedYear: 1993,
    arena: 'American Airlines Center',
    city: 'Dallas, TX',
    franchiseId: 15,
    previousNames: [{ name: 'Minnesota North Stars', years: '1967–1993' }],
  },
  DET: {
    abbrev: 'DET',
    name: 'Detroit Red Wings',
    foundedYear: 1932,
    arena: 'Little Caesars Arena',
    city: 'Detroit, MI',
    franchiseId: 12,
    previousNames: [
      { name: 'Detroit Cougars', years: '1926–1930' },
      { name: 'Detroit Falcons', years: '1930–1932' },
    ],
  },
  EDM: {
    abbrev: 'EDM',
    name: 'Edmonton Oilers',
    foundedYear: 1979,
    arena: 'Rogers Place',
    city: 'Edmonton, AB',
    franchiseId: 25,
  },
  FLA: {
    abbrev: 'FLA',
    name: 'Florida Panthers',
    foundedYear: 1993,
    arena: 'Amerant Bank Arena',
    city: 'Sunrise, FL',
    franchiseId: 33,
  },
  LAK: {
    abbrev: 'LAK',
    name: 'Los Angeles Kings',
    foundedYear: 1967,
    arena: 'Crypto.com Arena',
    city: 'Los Angeles, CA',
    franchiseId: 14,
  },
  MIN: {
    abbrev: 'MIN',
    name: 'Minnesota Wild',
    foundedYear: 2000,
    arena: 'Xcel Energy Center',
    city: 'Saint Paul, MN',
    franchiseId: 37,
  },
  MTL: {
    abbrev: 'MTL',
    name: 'Montreal Canadiens',
    foundedYear: 1909,
    arena: 'Bell Centre',
    city: 'Montreal, QC',
    franchiseId: 1,
  },
  NSH: {
    abbrev: 'NSH',
    name: 'Nashville Predators',
    foundedYear: 1998,
    arena: 'Bridgestone Arena',
    city: 'Nashville, TN',
    franchiseId: 34,
  },
  NJD: {
    abbrev: 'NJD',
    name: 'New Jersey Devils',
    foundedYear: 1982,
    arena: 'Prudential Center',
    city: 'Newark, NJ',
    franchiseId: 23,
    previousNames: [
      { name: 'Kansas City Scouts', years: '1974–1976' },
      { name: 'Colorado Rockies', years: '1976–1982' },
    ],
  },
  NYI: {
    abbrev: 'NYI',
    name: 'New York Islanders',
    foundedYear: 1972,
    arena: 'UBS Arena',
    city: 'Elmont, NY',
    franchiseId: 22,
  },
  NYR: {
    abbrev: 'NYR',
    name: 'New York Rangers',
    foundedYear: 1926,
    arena: 'Madison Square Garden',
    city: 'New York, NY',
    franchiseId: 10,
  },
  OTT: {
    abbrev: 'OTT',
    name: 'Ottawa Senators',
    foundedYear: 1992,
    arena: 'Canadian Tire Centre',
    city: 'Ottawa, ON',
    franchiseId: 30,
  },
  PHI: {
    abbrev: 'PHI',
    name: 'Philadelphia Flyers',
    foundedYear: 1967,
    arena: 'Wells Fargo Center',
    city: 'Philadelphia, PA',
    franchiseId: 16,
  },
  PIT: {
    abbrev: 'PIT',
    name: 'Pittsburgh Penguins',
    foundedYear: 1967,
    arena: 'PPG Paints Arena',
    city: 'Pittsburgh, PA',
    franchiseId: 17,
  },
  SEA: {
    abbrev: 'SEA',
    name: 'Seattle Kraken',
    foundedYear: 2021,
    arena: 'Climate Pledge Arena',
    city: 'Seattle, WA',
    franchiseId: 39,
  },
  SJS: {
    abbrev: 'SJS',
    name: 'San Jose Sharks',
    foundedYear: 1991,
    arena: 'SAP Center',
    city: 'San Jose, CA',
    franchiseId: 29,
  },
  STL: {
    abbrev: 'STL',
    name: 'St. Louis Blues',
    foundedYear: 1967,
    arena: 'Enterprise Center',
    city: 'St. Louis, MO',
    franchiseId: 18,
  },
  TBL: {
    abbrev: 'TBL',
    name: 'Tampa Bay Lightning',
    foundedYear: 1992,
    arena: 'Amalie Arena',
    city: 'Tampa, FL',
    franchiseId: 31,
  },
  TOR: {
    abbrev: 'TOR',
    name: 'Toronto Maple Leafs',
    foundedYear: 1927,
    arena: 'Scotiabank Arena',
    city: 'Toronto, ON',
    franchiseId: 5,
    previousNames: [
      { name: 'Toronto Arenas', years: '1917–1919' },
      { name: 'Toronto St. Patricks', years: '1919–1927' },
    ],
  },
  UTA: {
    abbrev: 'UTA',
    name: 'Utah Mammoth',
    foundedYear: 2024,
    arena: 'Delta Center',
    city: 'Salt Lake City, UT',
    franchiseId: 40,
    previousNames: [{ name: 'Utah Hockey Club', years: '2024–2025' }],
  },
  VAN: {
    abbrev: 'VAN',
    name: 'Vancouver Canucks',
    foundedYear: 1970,
    arena: 'Rogers Arena',
    city: 'Vancouver, BC',
    franchiseId: 20,
  },
  VGK: {
    abbrev: 'VGK',
    name: 'Vegas Golden Knights',
    foundedYear: 2017,
    arena: 'T-Mobile Arena',
    city: 'Las Vegas, NV',
    franchiseId: 38,
  },
  WSH: {
    abbrev: 'WSH',
    name: 'Washington Capitals',
    foundedYear: 1974,
    arena: 'Capital One Arena',
    city: 'Washington, DC',
    franchiseId: 24,
  },
  WPG: {
    abbrev: 'WPG',
    name: 'Winnipeg Jets',
    foundedYear: 2011,
    arena: 'Canada Life Centre',
    city: 'Winnipeg, MB',
    franchiseId: 35,
    previousNames: [{ name: 'Atlanta Thrashers', years: '1999–2011' }],
  },

  // ─── Modern-Era Defunct Teams (1967–present) ────────────────────────────
  HFD: {
    abbrev: 'HFD',
    name: 'Hartford Whalers',
    foundedYear: 1979,
    arena: 'Hartford Civic Center',
    city: 'Hartford, CT',
    isDefunct: true,
    yearsActive: '1979–1997',
    franchiseId: 26,
  },
  QUE: {
    abbrev: 'QUE',
    name: 'Quebec Nordiques',
    foundedYear: 1979,
    arena: 'Colisée Pepsi',
    city: 'Quebec City, QC',
    isDefunct: true,
    yearsActive: '1979–1995',
    franchiseId: 27,
  },
  ATL: {
    abbrev: 'ATL',
    name: 'Atlanta Thrashers',
    foundedYear: 1999,
    arena: 'Philips Arena',
    city: 'Atlanta, GA',
    isDefunct: true,
    yearsActive: '1999–2011',
    franchiseId: 35,
  },
  WIN: {
    abbrev: 'WIN',
    name: 'Winnipeg Jets',
    foundedYear: 1979,
    arena: 'Winnipeg Arena',
    city: 'Winnipeg, MB',
    isDefunct: true,
    yearsActive: '1979–1996',
    franchiseId: 28,
  },
  PHX: {
    abbrev: 'PHX',
    name: 'Phoenix Coyotes',
    foundedYear: 1996,
    arena: 'America West Arena / Jobing.com Arena',
    city: 'Phoenix / Glendale, AZ',
    isDefunct: true,
    yearsActive: '1996–2014',
    franchiseId: 28,
  },
  ARI: {
    abbrev: 'ARI',
    name: 'Arizona Coyotes',
    foundedYear: 2014,
    arena: 'Mullett Arena / Gila River Arena',
    city: 'Tempe / Glendale, AZ',
    isDefunct: true,
    yearsActive: '2014–2024',
    franchiseId: 28,
  },
  MNS: {
    abbrev: 'MNS',
    name: 'Minnesota North Stars',
    foundedYear: 1967,
    arena: 'Met Center',
    city: 'Bloomington, MN',
    isDefunct: true,
    yearsActive: '1967–1993',
    franchiseId: 15,
  },
  AFM: {
    abbrev: 'AFM',
    name: 'Atlanta Flames',
    foundedYear: 1972,
    arena: 'Omni Coliseum',
    city: 'Atlanta, GA',
    isDefunct: true,
    yearsActive: '1972–1980',
    franchiseId: 21,
  },
  KCS: {
    abbrev: 'KCS',
    name: 'Kansas City Scouts',
    foundedYear: 1974,
    arena: 'Kemper Arena',
    city: 'Kansas City, MO',
    isDefunct: true,
    yearsActive: '1974–1976',
    franchiseId: 23,
  },
  CLR: {
    abbrev: 'CLR',
    name: 'Colorado Rockies',
    foundedYear: 1976,
    arena: 'McNichols Sports Arena',
    city: 'Denver, CO',
    isDefunct: true,
    yearsActive: '1976–1982',
    franchiseId: 23,
  },
  CLE: {
    abbrev: 'CLE',
    name: 'Cleveland Barons',
    foundedYear: 1976,
    arena: 'Richfield Coliseum',
    city: 'Richfield, OH',
    isDefunct: true,
    yearsActive: '1976–1978',
    franchiseId: 13,
  },
  CGS: {
    abbrev: 'CGS',
    name: 'California Golden Seals',
    foundedYear: 1970,
    arena: 'Oakland-Alameda County Coliseum Arena',
    city: 'Oakland, CA',
    isDefunct: true,
    yearsActive: '1970–1976',
    franchiseId: 13,
    previousNames: [{ name: 'Oakland Seals', years: '1967–1970' }],
  },
  OAK: {
    abbrev: 'OAK',
    name: 'Oakland Seals',
    foundedYear: 1967,
    arena: 'Oakland-Alameda County Coliseum Arena',
    city: 'Oakland, CA',
    isDefunct: true,
    yearsActive: '1967–1970',
    franchiseId: 13,
  },

  // ─── Original Six / Early-Era Defunct Teams ──────────────────────────────
  NYA: {
    abbrev: 'NYA',
    name: 'New York Americans',
    foundedYear: 1925,
    arena: 'Madison Square Garden',
    city: 'New York, NY',
    isDefunct: true,
    yearsActive: '1925–1941',
    franchiseId: 8,
  },
  BRK: {
    abbrev: 'BRK',
    name: 'Brooklyn Americans',
    foundedYear: 1941,
    arena: 'Madison Square Garden',
    city: 'Brooklyn, NY',
    isDefunct: true,
    yearsActive: '1941–1942',
    franchiseId: 8,
  },
  MMR: {
    abbrev: 'MMR',
    name: 'Montreal Maroons',
    foundedYear: 1924,
    arena: 'Montreal Forum',
    city: 'Montreal, QC',
    isDefunct: true,
    yearsActive: '1924–1938',
    franchiseId: 7,
  },
  SLE: {
    abbrev: 'SLE',
    name: 'St. Louis Eagles',
    foundedYear: 1934,
    arena: 'St. Louis Arena',
    city: 'St. Louis, MO',
    isDefunct: true,
    yearsActive: '1934–1935',
    franchiseId: 3,
    previousNames: [{ name: 'Ottawa Senators (1917)', years: '1917–1934' }],
  },
  SEN: {
    abbrev: 'SEN',
    name: 'Ottawa Senators',
    foundedYear: 1917,
    arena: 'Ottawa Auditorium',
    city: 'Ottawa, ON',
    isDefunct: true,
    yearsActive: '1917–1934',
    franchiseId: 3,
  },
  HAM: {
    abbrev: 'HAM',
    name: 'Hamilton Tigers',
    foundedYear: 1920,
    arena: 'Barton Street Arena',
    city: 'Hamilton, ON',
    isDefunct: true,
    yearsActive: '1920–1925',
    franchiseId: 4,
  },
  QBD: {
    abbrev: 'QBD',
    name: 'Quebec Bulldogs',
    foundedYear: 1919,
    arena: 'Quebec Arena',
    city: 'Quebec City, QC',
    isDefunct: true,
    yearsActive: '1919–1920',
    franchiseId: 4,
  },
  PIR: {
    abbrev: 'PIR',
    name: 'Pittsburgh Pirates',
    foundedYear: 1925,
    arena: 'Duquesne Gardens',
    city: 'Pittsburgh, PA',
    isDefunct: true,
    yearsActive: '1925–1930',
    franchiseId: 9,
  },
  QUA: {
    abbrev: 'QUA',
    name: 'Philadelphia Quakers',
    foundedYear: 1930,
    arena: 'Philadelphia Arena',
    city: 'Philadelphia, PA',
    isDefunct: true,
    yearsActive: '1930–1931',
    franchiseId: 9,
    previousNames: [{ name: 'Pittsburgh Pirates', years: '1925–1930' }],
  },
  TAN: {
    abbrev: 'TAN',
    name: 'Toronto Arenas',
    foundedYear: 1917,
    arena: 'Arena Gardens',
    city: 'Toronto, ON',
    isDefunct: true,
    yearsActive: '1917–1919',
    franchiseId: 5,
  },
  TSP: {
    abbrev: 'TSP',
    name: 'Toronto St. Patricks',
    foundedYear: 1919,
    arena: 'Arena Gardens',
    city: 'Toronto, ON',
    isDefunct: true,
    yearsActive: '1919–1927',
    franchiseId: 5,
  },
  DCG: {
    abbrev: 'DCG',
    name: 'Detroit Cougars',
    foundedYear: 1926,
    arena: 'Border Cities Arena / Olympia Stadium',
    city: 'Detroit, MI',
    isDefunct: true,
    yearsActive: '1926–1930',
    franchiseId: 12,
  },
  DFL: {
    abbrev: 'DFL',
    name: 'Detroit Falcons',
    foundedYear: 1930,
    arena: 'Olympia Stadium',
    city: 'Detroit, MI',
    isDefunct: true,
    yearsActive: '1930–1932',
    franchiseId: 12,
  },
  MWN: {
    abbrev: 'MWN',
    name: 'Montreal Wanderers',
    foundedYear: 1917,
    arena: 'Westmount Arena',
    city: 'Montreal, QC',
    isDefunct: true,
    yearsActive: '1917–1918',
    franchiseId: 2,
  },
}

// All teams ever (for search) — current + historical
export const ALL_NHL_TEAMS: {
  abbrev: string
  name: string
  isDefunct?: boolean
  yearsActive?: string
}[] = [
  // Current 32
  { abbrev: 'ANA', name: 'Anaheim Ducks' },
  { abbrev: 'BOS', name: 'Boston Bruins' },
  { abbrev: 'BUF', name: 'Buffalo Sabres' },
  { abbrev: 'CAR', name: 'Carolina Hurricanes' },
  { abbrev: 'CGY', name: 'Calgary Flames' },
  { abbrev: 'CHI', name: 'Chicago Blackhawks' },
  { abbrev: 'COL', name: 'Colorado Avalanche' },
  { abbrev: 'CBJ', name: 'Columbus Blue Jackets' },
  { abbrev: 'DAL', name: 'Dallas Stars' },
  { abbrev: 'DET', name: 'Detroit Red Wings' },
  { abbrev: 'EDM', name: 'Edmonton Oilers' },
  { abbrev: 'FLA', name: 'Florida Panthers' },
  { abbrev: 'LAK', name: 'Los Angeles Kings' },
  { abbrev: 'MIN', name: 'Minnesota Wild' },
  { abbrev: 'MTL', name: 'Montreal Canadiens' },
  { abbrev: 'NSH', name: 'Nashville Predators' },
  { abbrev: 'NJD', name: 'New Jersey Devils' },
  { abbrev: 'NYI', name: 'New York Islanders' },
  { abbrev: 'NYR', name: 'New York Rangers' },
  { abbrev: 'OTT', name: 'Ottawa Senators' },
  { abbrev: 'PHI', name: 'Philadelphia Flyers' },
  { abbrev: 'PIT', name: 'Pittsburgh Penguins' },
  { abbrev: 'SEA', name: 'Seattle Kraken' },
  { abbrev: 'SJS', name: 'San Jose Sharks' },
  { abbrev: 'STL', name: 'St. Louis Blues' },
  { abbrev: 'TBL', name: 'Tampa Bay Lightning' },
  { abbrev: 'TOR', name: 'Toronto Maple Leafs' },
  { abbrev: 'UTA', name: 'Utah Mammoth' },
  { abbrev: 'VAN', name: 'Vancouver Canucks' },
  { abbrev: 'VGK', name: 'Vegas Golden Knights' },
  { abbrev: 'WSH', name: 'Washington Capitals' },
  { abbrev: 'WPG', name: 'Winnipeg Jets' },
  // Modern defunct
  { abbrev: 'HFD', name: 'Hartford Whalers', isDefunct: true, yearsActive: '1979–1997' },
  { abbrev: 'QUE', name: 'Quebec Nordiques', isDefunct: true, yearsActive: '1979–1995' },
  { abbrev: 'ATL', name: 'Atlanta Thrashers', isDefunct: true, yearsActive: '1999–2011' },
  { abbrev: 'WIN', name: 'Winnipeg Jets (1979)', isDefunct: true, yearsActive: '1979–1996' },
  { abbrev: 'PHX', name: 'Phoenix Coyotes', isDefunct: true, yearsActive: '1996–2014' },
  { abbrev: 'ARI', name: 'Arizona Coyotes', isDefunct: true, yearsActive: '2014–2024' },
  { abbrev: 'MNS', name: 'Minnesota North Stars', isDefunct: true, yearsActive: '1967–1993' },
  { abbrev: 'AFM', name: 'Atlanta Flames', isDefunct: true, yearsActive: '1972–1980' },
  { abbrev: 'KCS', name: 'Kansas City Scouts', isDefunct: true, yearsActive: '1974–1976' },
  { abbrev: 'CLR', name: 'Colorado Rockies', isDefunct: true, yearsActive: '1976–1982' },
  { abbrev: 'CLE', name: 'Cleveland Barons', isDefunct: true, yearsActive: '1976–1978' },
  { abbrev: 'CGS', name: 'California Golden Seals', isDefunct: true, yearsActive: '1970–1976' },
  { abbrev: 'OAK', name: 'Oakland Seals', isDefunct: true, yearsActive: '1967–1970' },
  // Early era defunct
  { abbrev: 'NYA', name: 'New York Americans', isDefunct: true, yearsActive: '1925–1941' },
  { abbrev: 'BRK', name: 'Brooklyn Americans', isDefunct: true, yearsActive: '1941–1942' },
  { abbrev: 'MMR', name: 'Montreal Maroons', isDefunct: true, yearsActive: '1924–1938' },
  { abbrev: 'SLE', name: 'St. Louis Eagles', isDefunct: true, yearsActive: '1934–1935' },
  { abbrev: 'SEN', name: 'Ottawa Senators (1917)', isDefunct: true, yearsActive: '1917–1934' },
  { abbrev: 'HAM', name: 'Hamilton Tigers', isDefunct: true, yearsActive: '1920–1925' },
  { abbrev: 'QBD', name: 'Quebec Bulldogs', isDefunct: true, yearsActive: '1919–1920' },
  { abbrev: 'PIR', name: 'Pittsburgh Pirates', isDefunct: true, yearsActive: '1925–1930' },
  { abbrev: 'QUA', name: 'Philadelphia Quakers', isDefunct: true, yearsActive: '1930–1931' },
  { abbrev: 'TAN', name: 'Toronto Arenas', isDefunct: true, yearsActive: '1917–1919' },
  { abbrev: 'TSP', name: 'Toronto St. Patricks', isDefunct: true, yearsActive: '1919–1927' },
  { abbrev: 'DCG', name: 'Detroit Cougars', isDefunct: true, yearsActive: '1926–1930' },
  { abbrev: 'DFL', name: 'Detroit Falcons', isDefunct: true, yearsActive: '1930–1932' },
  { abbrev: 'MWN', name: 'Montreal Wanderers', isDefunct: true, yearsActive: '1917–1918' },
]
